### ISSUE TITLE
Build app for Windows

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#105]
Please, build the first release for Windows system (64-bit only):

- <s>`ldm-0.x.y-win.msi` as a stand-alone installer for Windows</s> (**done**),
- `ldm-0.x.y-win.zip` as ready-to-run version packed to archive.

Once done, please start releasing this file type along with others in our [Releases](https://github.com/niner-games/lost-dutchman-mine/releases) section. Thank you!

**Comment by MadejaMaciej** [comment]
All done in release 0.2.1
