### ISSUE TITLE
Build app for Android

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#106]
Please, build the first release [for Android system](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Platforms#android) (64-bit only):

- `ldm-0.x.y-linux.apk` as a stand-alone installable version, ready to be shipped to Google Play store.

Once done, please start releasing this file type along with others in our [Releases](https://github.com/niner-games/lost-dutchman-mine/releases) section. Thank you!

**Comment by MadejaMaciej** [comment]
Done and tested in #20

**Comment by MadejaMaciej** [comment]
Need to be moved to persistent tasks
