### ISSUE TITLE
Silesian state flag

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#108]
## Overview

@mrfatguy could you provide silesian state flag image/icon?

**Comment by mrfatguy** [comment]
Sure thing, here you have it:

- [Flat. SX. Coat of Arms.png](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/4e73ada2-c053-4642-8c00-005ca69ede80)
- [Flat. SX. Simple.png](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/a1810f0f-e3be-454a-be43-0ccf9e4dce3c)

Though I have no idea, for what do you need it! :)
