### ISSUE TITLE
Build app for web

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#110]
## Overview

Please, build app for web and add static files as a zip to releases once ready.
- `ldm-0.x.y-web.zip`

**Comment by MadejaMaciej** [comment]
We shoululd be able to use the same code as in desktop app.

**Comment by MadejaMaciej** [comment]
To use it, copy contents of .webpack and transfer it to server/run index.html file

**Comment by mrfatguy** [comment]
Either I am blind or I don't see `.webpack` folder in repo. Can you link it or provide full path?

**Comment by MadejaMaciej** [comment]
@mrfatguy it was comment for myself so I will not forget about it :) 

I will put the zip with filesto use in next (0.2.2) release

webpack is in gitignore, as it changes each time we change anything in app (it recreates assets and bundles code used), so it shouldn't really land on git. I will provide you a temporary build here in zip.

To play unpack it and open renderer->main_window-> index.html file in browser.   NOTE that I need to fix the splash screen sound for web (there is already ticket for that).

[Archive.zip](https://github.com/niner-games/lost-dutchman-mine/files/14757714/Archive.zip)

**Comment by mrfatguy** [comment]
Thanks, tested, works just fine. Some minor details provided over email. OK, so waiting for the next release and official `ldm-x.y.z-web.zip`.
