### ISSUE TITLE
Sounds not working in web build

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#111]

**Comment by MadejaMaciej** [comment]
It is bigger problem than I thought. Basically web browser automatically blocks any sound if user hasn't clicked anything. So for work around I basically set up starting screen for webbrowser that says to play a game click any button and then splash screen happens.

**Comment by mrfatguy** [comment]
Stimulating click like in jQuery's `$('background').click()` is not an option?

**Comment by MadejaMaciej** [comment]
Unfortunately not, it detects that this was not actual interaction from client. It has to be some kind of interaction, click, mouse move, etc. We cannot rely on mouse move so we have to listen for clicks.

**Comment by mrfatguy** [comment]
What about making an animation (.mp4 file) and playing it? Can you auto-start MP4, MKV etc. video with sound without any user interaction?

**Comment by MadejaMaciej** [comment]
Yes, we can start a muted video any time. We just cannot play sounds without user interaction, as it is seen as "annoying" for the user.

**Comment by MadejaMaciej** [comment]
But again, without any interaction from user, even video end it will just not work.

**Comment by mrfatguy** [comment]
OK, I am working on some idea. Just give me some time.

What about _second_ movie / sound / effect / animation / video? If user clicks and you successfully show our logo _with sound_ and then you would like to play some other audio file (on the same screen), can you trigger it automatically (after first "user interaction" / click)? Or we must have user click / tap / press key) any time we want to trigger some mp3 playout?

**Comment by MadejaMaciej** [comment]
So basically it is limited only to first interaction. So after user clicks something once we can play any sound we like. 

Therefore what I did is before splash screen I created (for now) empty screen with text click anything to start a game. It only shows in browsers, so electron app is not affected by that, as there we can play any sounds we like. The same mobile version.

**Comment by MadejaMaciej** [comment]
I can't think of any other workarounds for the moment - and for what I have found on internet it seems that this is "desired" workaround. We could listen for mousemove for example, but we cannot guarantee that user will move it at all, therefore I would prefer to use on browser this starting screen before splash. 

It is as well most likely to not change in the future, as other workarounds might marked as not desired and blocked later.

**Comment by mrfatguy** [comment]
I totally understand this and eagerly agree with [this blockade](https://imagekit.io/blog/html-video-autoplay/). As a web user / web game player I don't want anything to play by itself when it is opened in some tab, before I actually interact with it. So the below is not a way for looking for an workaround, but rather a kind of _lessons learnt" for future.

Ideas:

1. See, if you can listen for [`DOMContentLoaded` event](https://stackoverflow.com/a/11936919/1469208) or use [`$(document).bind('ready', function() {});`](https://stackoverflow.com/q/11523359/1469208) and trigger playing sound from there (unless you have already checked it; then skip this point).

2. Check, if you can listen for [main window's resize](https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event)? Chances that you start game with exactly the same dimensions as user currently have its browser set are minimal. I have heard that `onResize()` event is triggered by Javascript / DOM **any time** new URL loads.

3. See, if you can listen for [`visibilitychange` event](https://stackoverflow.com/a/73915025/1469208) and make use of it.

4. Check, if you can [auto-play audio (or video) muted](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide) and then use [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) (in one of the above events?) to increase volume to some level?

5. See, if [this old trick with playing silence in an iframe](https://olafwempe.com/how-to-enable-audio-and-video-autoplay-with-sound-in-chrome-and-other-browsers-in-2019/) is going to work for you.

BTW: Last page (5) has a bug (or an intentionally hidden content). When you open it, it seems empty. Open Dev Tools in your browser (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>) click on "empty" page, locate `<div id="ajax-loading-screen">` in page source and hit <kbd>Del</kbd> to delete this HTML element. Then you'll have full access to page content.

The trick does work (when you click on the example links and go to <https://olafwempe.com/> the background music truly auto-starts), but again the entire page is hidden behind empty full-screen overlay. This is most likely this "silence"-iframe that the article talks about.

If this will work in our game and **provided that you DO WANT to break browser limitations and auto-start logo tune** then you maybe forced to hide/close this iframe (or `<div id="ajax-loading-screen">` element) programmatically.

If you don't want to break the rules / limitations then consider this task as completed / closed. And we will re-use that additional screen (that you have prepared already, with "click to start") to display "early alpha game" info.

**Comment by MadejaMaciej** [comment]
Already tried 4 of the first steps, nothing of it does work. 5 step should work, but in that case I would prefer to use official solution so wait for user click, as iframe may break in future.

Will leave it as closed and done and we should be able to use this screen as info popup as well, I just need to modularize it, as for now it just display static text without any graphics. 

I'll use for that tasj ticket that already existst.
