### ISSUE TITLE
Incorrect app's icon for desktop version

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#115]
Please, replace current icon (Electron's default) for [Windows, macOS and Linux](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#desktop) with [our own icon](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#assets).

Please, remember about setting correct (our own) icons for both [app icons](https://www.electronforge.io/guides/create-and-add-icons#setting-the-app-icon) and [installer icons](https://www.electronforge.io/guides/create-and-add-icons#configuring-installer-icons).

**Comment by MadejaMaciej** [comment]
Will be solved in #79

**Comment by MadejaMaciej** [comment]
It will show only in build, not on dev version as electron has some strange problems.
