### ISSUE TITLE
Add basic information on environment and building to our Wiki

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#119]
@MadejaMaciej Please, provide the necessary basic information to [our Wiki](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building). Especially to the: 

- [Initial Steps](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#initial-steps)
- [Preparing Environment](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#preparing-environment)
- [Git Flow and Pull Requests](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#git-flow-and-pull-requests)
- [Building for Desktop](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#building-for-desktop)
- [Building and Publishing for Web](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#building-and-publishing-for-web)
- [Testing](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#testing) → [Desktop](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#desktop)

sections. So that can anyone is able to setup minimum environments to code further, test our game and build it's binaries.

Some questions, areas and issues that should be covered:

- What do you need to start? What to install and in what order?
- What is the suggested editor, software, IDE for coding?
- The minimum steps needed to go _from-code-to-PR_
- What steps are needed to go _from-code-to-exe_ the fastest way?
- What is the suggested method and software to test?

Should you find anything else also important, please, don't hesitate and add it as well.

Don't worry about formal form, possible spelling mistakes, grammar etc. Put that all on me. Thank you.

**Comment by MadejaMaciej** [comment]
Changes added to https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building - it might require some rewording.
