### ISSUE TITLE
Multi-language settings screen

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#120]
Please, perform basic research on providing multi-language support to [settings screen](https://github.com/niner-games/lost-dutchman-mine/wiki/Game.-Settings):

1. How can you capture (in `OnKeyPress` event?) **different key presses** for **the same item** based on currently selected language? For example, how to trigger _Save Game_ feature after user presses:

    - <kbd>S</kbd> when language is set to _English_
    - <kbd>Z</kbd> when language is set to _Polish_

2. What numeric codes you will receive (again in `OnKeyPress` event?) for every _Cyrylic_ letter, if language is set to [_Ukrainian_](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Translations#ukrainian).

     - The same goes for [_Silesian_](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Translations#silesian), [_Spanish_](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Translations#spanish), [_French_](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Translations#french), [_German_](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Translations#german) and [_Polish_](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Translations#german) language
     - Though it is less likely that basic operations (menu items) will have shortcuts using national-diacritics

3. What software (or virtual keyboard) you need to have installed in order to test the above (on contrary to regular tests you cannot just copy-paste some character to mimic keypress)?

This is just an informative or preparation task. You can complete it separately or merge it as a part of #14.

**Comment by MadejaMaciej** [comment]
So what I get in all of the cases (or rather on what I operate is a key code, which is different depnding on key clicked), so it will be different for S, Z and any Ukrainian key. 

It's enough to just install the virtual keyboard system. 

To diffrentiate after keypress I will get the code and then check current language, which will let me assign correct behaviour depending on language.
