### ISSUE TITLE
Unpacking native Node modules from your Forge app's ASAR archive

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#121]
Please, research the possibility of using [Auto Unpack Native Modules Plugin](https://www.electronforge.io/config/plugins/auto-unpack-natives) to reduce loading times and disk consumption on our users' machines.

Also, please check, if there is any possibility of reducing `.asar` file at all? If we can remove some unused Node modules from it to reduce size of the installers / shops / native files shipped with each build.

**Comment by MadejaMaciej** [comment]
It happens that we are already using it, but we could get rid off it if needed. Modules then will be packed directly to the codebase tho, so it might be bad for performence and disk consumption.

Unfortunately after checking at this moment we have only modules we are using, so nothing to remove there.
