### ISSUE TITLE
Using Electronegativity plugin to find any security issues in our code

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#122]
Please, research the possibility of using [Electronegativity](https://github.com/doyensec/electronegativity#electronegativity) tool through [Electronegativity Plugin](https://www.electronforge.io/config/plugins/electronegativity) for looking for any possible misconfigurations or security anti-patterns in our game's code prior to each new release.

**Comment by MadejaMaciej** [comment]
We have a ESLINT already installed that let's as check for antipatterns in our code but will set it up as well.
