### ISSUE TITLE
Using Snapcraft Publisher

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#123]
Please, research the possibility of using [Snapcraft Publisher](https://www.electronforge.io/config/publishers/snapcraft) and the modifications necessary to our _publish-to-app-stores_ pipeline, so we can publish Linux version of our game to the [Snap Store](https://snapcraft.io/store), just as we do with Microsoft Store, Google Play, App Store etc.

**Comment by MadejaMaciej** [comment]
They have pretty nice docs about it. Process seems similar to any other stores.

For reference: https://snapcraft.io/docs/snapcraft-quickstart 

There is even way to setup the github worker to push new version of software to the store once it has been merged to main, but for now I think we will skip it. 

It is free and we should be able to sign it by our own/or certificate we bought.

https://snapcraft.io/blog/want-to-publish-a-snap-heres-a-list-of-dos-and-donts

The difference is that there are different "shards" to where we can publish the game, so for example - in the shard-store shard, hello-world shard and so on. 

There are differences in terms of structure of files, but it seems thats almost all of them.
