### ISSUE TITLE
Investigate installed PC/Windows version of our game

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#124]
Our game in current version resides after successful installation in **three** different folders:

- `c:\Users\[username]\AppData\Roaming\california-49er-desktop-v1` -- **6,18 MB** / many files
- `c:\Users\[username]\AppData\Local\Programs\california-49er-desktop-v1` -- **728 MB** / many files
- `c:\Users\[username]\AppData\Local\california-49er-desktop-v1-updater` -- **366 MB** / just one file: `installer.exe`

And occupies approx. **1.1 GB** of disk spaces on user's destination device.

Please, investigate if this is as it supposed to be (i.e., if every Electron app does something like that).

**Comment by MadejaMaciej** [comment]
It depends solely on bundler, later on I'll try to slim it and get rid off multiple directories.
