### ISSUE TITLE
Fix Lost Pixelized Font's default settings

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#136]
It turned out that default font settings implemented in #129 were measured at a too low screen resolution.

The correct ones are:

- `font-size`: `36 pt`
- [font scale](https://stackoverflow.com/questions/16056591/font-scaling-based-on-size-of-container/74977615#74977615): `150%`
- `font-weight`: `normal`
- `line-height`: `42 pt`
- `font-family`: `Lost Pixelized Font`
- `color`: `#CFAE6D` (207, 174, 109 in RGB model)

Please, implement them. Thank you!

For more details, please take a look at [this article](https://github.com/niner-games/lost-dutchman-mine/wiki/Interface.-Screen#font) at our Wiki.

**Comment by MadejaMaciej** [comment]
Changed it but it seems rather big. Are you sure it should be like this? 
![Screenshot 2024-04-13 at 17 58 20](https://github.com/niner-games/lost-dutchman-mine/assets/48794984/3441e879-e787-453b-8eda-ff8d279587c0)

Closing the ticket for now as it has been implemented. If we decide to change resolution let's do next ticket.
