### ISSUE TITLE
Add favicon for mac

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#144]
It has to have 512px width and height

**Comment by mrfatguy** [comment]
@MadejaMaciej It seems that you have made this 512x512 icon yourself. Keep in mind that [we have all the assets prepared](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#assets) for all the platforms, based on what [Electron guide specifies](https://www.electronforge.io/guides/create-and-add-icons#supported-formats).

Make sure that you have it working, as you have used [.png file](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/1f616da5-3e74-455f-b4b6-abc4cb7ccaf6) where Electron guide requires you to use [.icns file](https://github.com/niner-games/lost-dutchman-mine/files/14813076/i512.zip) instead.

Reopening. Close again after you verify that this truly works on MacOS. Thanks.

**Comment by MadejaMaciej** [comment]
It works, it doesn't matter from a long time, compiler just where playing tricks on me and would not compile as for windows and linux I had to use 256px one, and for mac 512px.
