### ISSUE TITLE
Add icon to linux build

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#146]
It is not loading currently after installation. Probably needs other properties or sizes additionally.

**Comment by mrfatguy** [comment]
Electron guide [says that](https://www.electronforge.io/guides/create-and-add-icons#supported-formats) 512x512 pixels _.png_ for Linux is correct.

Did you noticed [extra remarks for Linux](https://www.electronforge.io/guides/create-and-add-icons#linux)?

Configuring the path to your icon must be done in both package.json as well as in Electron's main process.

> **forge.config.js**:
> 
> ```typescript
> module.exports = {
>   // ...
>   makers: \[
>     {
>       name: '@electron-forge/maker-deb',
>         config: {
>           options: {
>             icon: '/path/to/icon.png'
>           }
>       }
>     }
>   ]
>   // ...
> }
> ```
> 
> The icon must be additionally loaded when instantiating your [BrowserWindow](https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions).
> 
> **main.js (Main Process)**:
> ```typescript
> const { BrowserWindow } = require('electron')
> 
> const win = new BrowserWindow({
>   // ...
>   icon: '/path/to/icon.png'
> })
> ```
>
> Once the path to the icon has been configured, build your project to generate your executable with either `npm run make`. 

I think this is important.

**Comment by MadejaMaciej** [comment]
We do not use forge anymore to build any of the apps, as electron-builder is just better and easier to work with. I had to look what to do about that, as just icon property should do the trick. Might be that I should use 512px as you said instead of 256px (windows default) and that is all.

BrowserWindow might be a good shout for every platform. Will check it.

**Comment by MadejaMaciej** [comment]
Think I found it:

icon String - The path to icon set directory or one png file, relative to the [build resources](https://www.electron.build/configuration/configuration#MetadataDirectories-buildResources) or to the project directory. The icon filename must contain the size (e.g. 32x32.png) of the icon. So it should be just 512x512.png instead of favicon.png.

**Comment by MadejaMaciej** [comment]
Unfortunately after some tries it didn't work, need to search for something else. Will pick it up again after I transfer and tweak code for mobile, so for a moment now will be "feature stop". 

After that I will be working on rest of the task that are In Progress first and then the rest from To Do and Backlog lists.
