### ISSUE TITLE
Specify email and homepage fields in pakcage.json

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#153]
## Overview

Please, specify email property in author property and homepage property (URL address) in package.json.

**Comment by MadejaMaciej** [comment]
@mrfatguy could you provide correct email and homepage adres we should use there. Linux build requires these fields.

**Comment by mrfatguy** [comment]
@MadejaMaciej Sure, but these are default and the same: `https://ninergames.com/` and `info@ninergames.com`.
