### ISSUE TITLE
Device orientation in mobile apps

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#159]
Please, implement a feature that enforces our mobile apps to run always and unconditionally in landscape orientation. Thank you!

Details: [Game's Startup Sequence](https://github.com/niner-games/lost-dutchman-mine/wiki/Game.-Startup-Sequence) → [Device Orientation](https://github.com/niner-games/lost-dutchman-mine/wiki/Game.-Startup-Sequence#device-orientation).

**Comment by MadejaMaciej** [comment]
Moving to done, as it will be part of #20
