### ISSUE TITLE
Find what need to be tweaked in mobile app code

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#20]
To create specific tasks

**Comment by MechanikGamer** [comment]
I can help you with React Native app

**Comment by MadejaMaciej** [comment]
Currently I am at stage of moving all of the files to react native (code-mobile) directory and just starting adjusting it so it will start showing something there for now. It is currently on branch #20 in rough (just React) stage. As we cannot use there plain HTML, we will need to change to use React Native Components, but we want to make it as similar to our electron/web app as possible. 

We might create some conflicts by working on it together, if you want to help on that - feel free to work on it. I really appreciate it!
