### ISSUE TITLE
Generate map for game

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#23]
## Overview

Please, implement a general map feature in our game.

This task is for creating map entity in the game's ecosystem only. There will be a separate tasks for the ability to switch between map and other locations only or for moving around the map and for other features and functionalities that belongs to the map.

## Narrative

- **As a** player
- **I want** be able to switch between map and locations
- **So that** I can navigate through desert and be able to use location-related functionalities

## Acceptance Criteria

The map entity exists in the application's ecosystem.

**Comment by trejder** [comment]
This is a pure coding task. Map assets will be provided in #24. Reassigning back to you, @MadejaMaciej.

**Comment by mrfatguy** [comment]
@MadejaMaciej It seems that map drawing is split into: gathering assets (#24) and implementing actual map (#23).

Now, it seems that you have implemented map already (#24 and #37), so this one (#23) can be closed as done or duplicate. Please, reopen, if I have missed something out.

**Comment by MadejaMaciej** [comment]
I will reopen thjis issue, as I still need to include it in the code
