### ISSUE TITLE
Updating Changelog

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#29]
@MadejaMaciej Please, try to remember about [updating CHANGELOG.md](https://github.com/niner-games/game-react-lost-dutchman-mine/edit/main/CHANGELOG.md) from time to time:

- Based on [closed issues](https://github.com/niner-games/game-react-lost-dutchman-mine/issues?q=is%3Aissue+is%3Aclosed)
- Once per bi-week sprint is enough or as often as you prefer (can be with every commit or branch merge, if you wish)
- Only important things (that adds real business value to the game), no side works like extracting images or researching, please

Game versioning -- simplified [sem-ver](https://semver.org/):

- _MAJOR_ -- never, single game version = single factory, so always `1`
- _MINOR_ -- +1 each time you successfully publish something to app stores
- _PATCH_ -- each two weeks (+1 per sprint)

Simplified, meaning auto-increase each sprint, no need to increase version number with real patches, hot-fixes etc.

**Comment by MadejaMaciej** [comment]
Shouldn't patch be each time I add something/fix something? I have a tool already setup that with PR created it increments what I want.

**Comment by MadejaMaciej** [comment]
Closed due to it being persisten task, no need to be "open"
