### ISSUE TITLE
Enhance startup logo screen

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#43]
## Overview

Please, implement logo / startup-screen with:

- [Logo](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Game.-Startup-Sequence#image) without credits
- Additional [text overlays](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Game.-Startup-Sequence#text-overlay)
- Playing [background tune](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Game.-Startup-Sequence#background-music)
- Functionality for player to be [able to break it and continue](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Game.-Startup-Sequence#user-interaction) to the next screen

## Narrative

- **As a** game player
- **I want** see original game logo and hear original intro tune
- **To** be able to glimpse into game climax from the very first seconds of my experience

**Comment by MadejaMaciej** [comment]
Currently we do not need loader (as amount of resources is minimal). If there will be need for that, we will create another ticket. 

Working on splash screen, sounds, version info and breaking the screen.
