### ISSUE TITLE
Moving sounds of character

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#47]
@mrfatguy could you extract sounds that character is doing while moving?

**Comment by mrfatguy** [comment]
@MadejaMaciej Already done and waiting for you! :) For walking left-right, see [here](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Player.-General#city) (under the image). For entering and leaving buildings see [here](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Player.-General#entry-or-exit-fade-effect) (under animation).
