### ISSUE TITLE
Create file with every possible in game string and it's translation

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#53]
@mrfatguy Could you create a file that have every string in game in english and it's ltranslation to other languages?

**Comment by mrfatguy** [comment]
Sure! But you need to provide or we need to agree on format, files structure, etc. I don't know what your code can parse? Are there any limitations or obstacles or you can generally parse everything that is in JSON format and is mutually agreed?

Is there any internationalization framework for translators inside React Native (like we have for [PHP's Yii 2 Framework](https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n)) that we can reuse? Or must we design something on our own?

Can we reuse [a solution used in Yii 2 framework](https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n#:~:text=Each%20PHP%20file%20corresponds%20to%20the%20messages%20of%20a%20single%20category):

1. One top-level `translations` folder in main repo's folder or somewhere else.
2. Subfolders in this folder that corresponds to each language, i.e. `pl`, `en`, `ua`, `sl`, etc.
3. Files in each subfolder matching a group or keyword, i.e. `mines`, `saloon`, `assay`, `map` etc.
4. Each file contains translations in form of simple JSON file where English translation is a key.
5. Inside your code you have a method that calls translation using group and English translation as a parameters.
6. Current in-game language is checked inside this method so there's no need to use as a parameter in each method's call.
7. If there's a translation missing for given language and/or group and/or string, English translation is always used by default.

Example simple translation file for `river` group and `pl` language (`translations\pl\river.json`):

```json
{
    "Too many items to carry!": "Zbyt wiele przedmiotów do niesienia",
    "Fish": "Łowienie",
    "Water": "Picie",
    "Pan": "Przesiewanie",
    "Exit": "Wyjście",
}
```

Example translation file for `end` group and `ua` language (`translations\ua\end.json`) with [multi-line support](https://stackoverflow.com/a/66531090/1469208):

```json
{
    "And so ends the life\\n\\nof yet another poor\\n\\nprospector who, like\\n\\nso many before him,\\n\\ndied looking for but\\n\\nnever finding the...\\n\\n\\n\\nLOST DUTCHMAN MINE": "І так закінчується життя\\n\\nще одного бідного\\n\\nстаратель, який, як\\n\\nтак багато до нього,\\n\\nпомер у пошуках але\\n\\nніколи не знайти...\\n\\n\\n\\nЗАГУБЛЕНА ГОЛЛАНДСЬКА МІНА",
    "Play Again?": "Грай знову?",
    "Yup": "Так",
    "Nope": "ні",
}
```

Example call of translation method in your code:

```node
let obj = sys.t('river', 'Too many items to carry!');
```

If you cannot parse such files or this solution doesn't suit you for any other reason, please provide yourself.

BTW: Translation of an app is a huge task that will have many subtasks and possible a number of bugs reported. Consider creating a milestone to group all translation-related tickets here on GitHub.

**Comment by MadejaMaciej** [comment]
This solution will suit me really well. Basically that is what I did and need. 

Could you create a separate task for locations then (anything that works for you) so we do not get lost where we are?

**Comment by mrfatguy** [comment]
@MadejaMaciej Can you be more specific on what do you mean by "task for locations"?

If you mean how many groups / files must be prepared for each translation then I'll suggest basing this on our [Wiki's right sidebar](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki) and using following files:

- `assay`
- `bank`
- `jail`
- `mercantile`
- `saloon`
- `stable`
- `doctor`
- `newspaper`
- `events`
- `river`
- `mines`
- `startup`
- `options`
- `credits`
- `health`
- `time`
- `other`

If you think that 17 files per each translation is too much or if you are asking about something else, then please provide some details in comments. Thank you.

**Comment by MadejaMaciej** [comment]
Basically that list looks fine - if we find other main locations/parts we can always add it to the next task - it does not make any difference for me from coding perspective. I'll need to adjust it to use nested translations, but it will not be a problem.

**Comment by MadejaMaciej** [comment]
Files has been created. Closing this ticket. We should create new one for each location. Details are adjusted in wiki.
