### ISSUE TITLE
Adjust translation system

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#54]
Implement the directory structure for different language files (do not use big one file, with every string).

Details: #53 and [Application. Translations](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Application.-Translations) page at wiki.

**Comment by mrfatguy** [comment]
Please, let me know, if you are done with developing translation system, so I can update our Wiki page:

- [Add correct paths](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Application.-Translations#paths) to translation files in repo
- Correct or update [translation examples](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Application.-Translations#examples)

Thank you!

**Comment by MadejaMaciej** [comment]
Examples will be okay, I'll adjust paths in a minute.
