### ISSUE TITLE
Markdown renderer with support for translations

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#56]
Please, implement [Markdown renderer](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Application.-Translations#translation-of-big-blocks-of-text) with support for translations and with some [additional extensions](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Application.-Translations#markdown-extensions). 

In addition to #54 we need to support whole-page translations (or [translation of big blocks of text](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Application.-Translations#translation-of-big-blocks-of-text)), based on Markdown language, for features like credits or newspaper.

The mechanism of actually displaying credits or newspaper will be handled by a separate tickets. This ticket is for introducing Markdown renderer to our application only.

Details are given in our Wiki: [Application. Translations → Translation of big blocks of text](https://github.com/niner-games/game-react-lost-dutchman-mine/wiki/Application.-Translations#translation-of-big-blocks-of-text).

**Comment by MadejaMaciej** [comment]
@mrfatguy ticket is done, I found nice MIT license plugin with full support of markdown. 

https://www.npmjs.com/package/react-markdown

You can provide translations/large blocks of code in Markdown format now

**Comment by MadejaMaciej** [comment]
P.S all tested and it works nicely.

**Comment by MadejaMaciej** [comment]
P.S all tested and it works nicely.

**Comment by mrfatguy** [comment]
@MadejaMaciej Does it support embedding HTML code and renders it correctly?

**Comment by MadejaMaciej** [comment]
Yes but you need to escape all the ` character so use backslash before it.

**Comment by mrfatguy** [comment]
OK, but HTML generally doesn't use backtick, right? So, basically speaking, this should work:

```markdown
<span style="font-size: #px">Lost Dutchman Mine</span>

A tale as old as _the desert itself_.
Legend says it holds a fortune **in gold**, just _waiting to be found_!

<div style="text-align: left">Copyright (c) 2024 by Niner Games</div>
```

Am I correct?

**Comment by MadejaMaciej** [comment]
sorry, I was thinking about 

```
code
```

Yes it works.
