### ISSUE TITLE
Assure correct pixel-to-pixel alignment across entire application

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#62]
It was [estimated](https://github.com/niner-games/lost-dutchman-mine/wiki/Interface.-Screen#pixel-ratio) that in 4K resolution (3840x2160 px) **pixel-per-pixel** (ppp) ratio is **11 pixels**. Meaning that _single in-game pixel cover the area of 11 x 11 pixels_.

Please, make sure that this is assured and respected in the entire game:

- No sprite's pixel may overlap background pixel in the middle etc.
- No animation could appear on smaller than 11 pixels "distance"
- All added objects (buttons, images) must align background or GUI interfaces to the 11x11 square

The above calculation and estimation is made for full-screen viewport in 4K resolution (3840x2160 px). For non-full-screen window in this resolution or for non-4K resolutions please adjust calculations and checks accordingly.

If this is already implemented and assured across entire app then please close this ticket as done.

**Comment by MadejaMaciej** [comment]
It will be assured once we created gui -> main elements are assured therefore closing the ticket.
