### ISSUE TITLE
Unable to start PC version of the game

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#72]
## Overview

When Microsoft Defender SmartScreen screen (#71) then game displays two error messages and doesn't startup at all:

> **Installation has failed**
> Unable to write to _c:\ProgramData\[username]\SquirrelTemp_ -- IT policies may be restricting access to this folder

And:

> **Installation has failed**
> Failed to extract installer

In my case the _c:\ProgramData\[username]_ folder is completely empty. If I manually create _SquirrelTemp_ inside it then game displays only second error (and also won't startup).

## Necessary steps

1. Start the game and pas SmartScreen warning (#71).

## Expected results

Game runs normally.

## Actual results

Game displays a serie of error messages.

## Screenshot or screencast

Error number 1:

![image](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/535637ff-342b-43d4-b714-cfb91ee99a30)

Error number 2:

![image](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/1a880f77-59d9-4ec2-8915-9d00b2b7f6f6)

### Computer

- System: **Windows 11 Pro (10.0.22631 Build 22631)**

**Comment by mrfatguy** [comment]
No change on my side! :(

**Comment by MadejaMaciej** [comment]
Will try to test it using computer not touched by me at all.

**Comment by MadejaMaciej** [comment]
Fix for that might be using different bundler.

https://www.electron.build/index.html

**Comment by MadejaMaciej** [comment]
And this seems promising. https://stackoverflow.com/questions/58918027/electron-winstaller-throws-the-system-cannot-find-the-path-specified-at-squirre
