### ISSUE TITLE
Build app for Linux

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#78]
Please, build the first release [for Linux system](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Platforms#linux) (64-bit only):

- `ldm-0.x.y-linux.deb` as a stand-alone installer for Linux,
- `ldm-0.x.y-linux..tar.gz` as ready-to-run version packed to archive.

Once done, please start releasing this file type along with others in our [Releases](https://github.com/niner-games/lost-dutchman-mine/releases) section. Thank you!

**Comment by MadejaMaciej** [comment]
It needs to be done on linux machine. 

Every build can only be done on machine with the system we need

**Comment by mrfatguy** [comment]
Already tested to be working -- #76.
