### ISSUE TITLE
Incorrect package's properties

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#79]
Please, fix incorrect package or build properties.

# AS-IS (Current status)

## 1. Installer program

1. Main window's title:  `california-49er-desktop-v1`
2. Folder created in %APPDATA%: `california-49er-desktop-v1`
3. Item added to "Add/Remove programs" list: `california-49er-desktop-v1`

## 2. Installed app's desktop icon

1. ~~Image: **Electron's default**~~ (descoped from this ticket)
2. Title: `california-49er-desktop-v1`
3. Company: `Maciej Madejczyk`
4. File description: `Lost dutchman mine game for desktop.`
5. ~~File version: `0.0.3.0` (unnecessary fourth digit)~~ // EDIT: It seems we cannot change this, as windows adds it by itself. Descoping.

## 3. Main game's window

1. Title: `Goldrush`.

# TO-BE (Expected results)

## 1. Installer program

1. Main window's title:  `Lost Dutchman Mine`
2. Folder created in %APPDATA%: `Niner Games\Lost Dutchman Mine` (notice dir\subdir scheme)
3. Item added to "Add/Remove programs" list: `Lost Dutchman Mine`

## 2. Installed app's desktop icon

1. ~~Image: **Game logo-based**~~ (→ [#115](https://github.com/niner-games/lost-dutchman-mine/issues/115), [#116](https://github.com/niner-games/lost-dutchman-mine/issues/116) and [#117](https://github.com/niner-games/lost-dutchman-mine/issues/117))
2. Title: `Lost Dutchman Mine` (without dot at the end)
3. Company: `Niner Games`
4. File description: `Lost Dutchman Mine`
5. ~~File version: `0.0.3`~~

## 3. Main game's window

1. Title: `Lost Dutchman Mine`

# Examples

Some examples on how does it look right now.

## Installed app's desktop icon

![example 1](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/71e0d057-75f9-4cb6-baa8-d1090bb630a3)

## App's destination folder name

![example 2](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/847fbc6c-f86d-4d07-83fd-ce6a696e1f50)

## Item in the "Add/remove programs" list:

![image](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/ff2148e3-bcf1-4b60-8492-6d763b1134c1)

## Main game's window

![example 3](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/abf1bbef-3272-48b6-9377-739f24e68dca)

**Comment by MadejaMaciej** [comment]
So after some extensive research, I would like to adjust scope of this ticket, that means getting right of point 5. It seems that windows mark File version with x.y.z.a code always and automatically and there is nothing we can do about it. There is the second property tho, that shows the correct version if that suits us. 

Is that okay?

This task is taking longer than I thought and is blocking me pretty strong, because of that code.

**Comment by mrfatguy** [comment]
If other points (1.1-1.3, 2.1-2.4 and 3.1) are completed then you can of course close this ticket as done! 🥇

**Comment by MadejaMaciej** [comment]
Need to adjust the directory structure still, but other things are done. Will do that and close the ticket then.

**Comment by MadejaMaciej** [comment]
Could not manage to get Folder -> subfolder to work. Can we have separate task for that, as this is not entirely  a property issue? It's a builder thing I would need to debug @mrfatguy

**Comment by mrfatguy** [comment]
> Could not manage to get Folder -> subfolder to work. Can we have separate task for that, as this is not entirely a property issue? It's a builder thing I would need to debug @mrfatguy

Done, sir! :] #142
