### ISSUE TITLE
New loader image

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#80]
Please, replace original Electron's loader image / animation:

<p align="center">
    <a href="https://github.com/niner-games/lost-dutchman-mine/assets/2903392/d52599f9-9ebc-4391-bbf2-ff99ca62a057">
        <img width="219" height="150" src="https://github.com/niner-games/lost-dutchman-mine/assets/2903392/d52599f9-9ebc-4391-bbf2-ff99ca62a057" alt="Logo of Niner Games company">
    </a>
</p>

With static company logo:

<p align="center">
    <a href="https://github.com/niner-games/lost-dutchman-mine/assets/2903392/721d35d7-3da3-4438-a373-a6954603aae9">
        <img width="219" height="150" src="https://github.com/niner-games/lost-dutchman-mine/assets/2903392/721d35d7-3da3-4438-a373-a6954603aae9" alt="Logo of Niner Games company">
    </a>
</p>

Source file (linked above) is rectangle, but (if possible) make our loader square. Pure white company logo on black text.

As for the dimensions, this doesn't matter really. You can use the same as original Electron's loader has, slightly bigger or our logo's original images. Please, make some tests and decide.

**Comment by MadejaMaciej** [comment]
We stopped using squirrel, so there is no such loading screen right now. Closing.
