### ISSUE TITLE
Thermometer's value is incorrectly drawn

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#85]
https://github.com/niner-games/lost-dutchman-mine/wiki/Interface.-Control-Panel

The bar that is suppose to denote current temperature is drawn to far to the left and "jumps" of the actual thermometer's bulb.

It is less noticeable in the default (windowed) app view:

<img width="79" alt="t1" src="https://github.com/niner-games/lost-dutchman-mine/assets/2903392/8b833e89-57de-4d78-af41-e25751cff1f1">

And much more when game is in full-screen mode:

<img width="91" alt="t2" src="https://github.com/niner-games/lost-dutchman-mine/assets/2903392/99f45d5d-cd87-4fd0-9dfc-0e7457c243f4">

In addition:

- temperature knob is using pale `#ff0000` red color which makes it flat while original game is using two colors:
    - `#ae0000` for the outset / border
    - `#ef0000` for the inset,
- the bulb image is missing
- the background image is cut without surrounding 1-pixel border which also makes the whole thermometer flat. 

Please, see the original image for reference: 

![image](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/c3e85a2a-e8f4-4923-92a1-e58c9db9f4dc)

Please, not that in-game temperature never drops below 30 F, so the bottom part of the thermometer (with bulb) can be drawn as static, all-the-time the same image:

![image](https://github.com/niner-games/lost-dutchman-mine/assets/2903392/b31e3012-b481-40eb-a161-eb8efa2ddc46)

More thermometer's images [can be found at our Wiki](https://github.com/niner-games/lost-dutchman-mine/wiki/Interface.-Control-Panel#thermometer).

**Comment by MechanikGamer** [comment]
Fixed it here #149

**Comment by MadejaMaciej** [comment]
We will need separate ticket for handling the temperature and height of the bar itself.
