### ISSUE TITLE
Player's animation starting from second keypress

### ISSUE THREAD

**Issue by mrfatguy** [niner-games/lost-dutchman-mine#97]
## Overview

When pressing <kbd>←</kbd> or <kbd>→</kbd> in a separate key-strokes, separated by a long pause then animation for a single key stroke is not run at all (it generally starts with approx. 1 second delay) and it causes player too look like it would be ice skating! It is moving around the town, some times even at great distances without any animation at all.

## Necessary steps

1. Start new game
2. Press <kbd>←</kbd> or <kbd>→</kbd> a couple of time with a longer pause in-between

## Expected results

Character animation is played from the first key stroke / second / frame and in this particular scenario it is played at all.

## Actual results

Animation is played from the second key stroke / second second and in this scenario is not visible at all.

**Comment by MadejaMaciej** [comment]
This will be fixed in #72 as it has overhaul of player movement and classes
